version: '3.8'

services:
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    environment:
      DB_SERVER_HOST: zabbix-db
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbixpass
      POSTGRES_DB: zabbix
      ZBX_STATSALLOWEDIP: 127.0.0.1/32
    ports:
      - "10051:10051"
    volumes:
      - zabbix-server-data:/var/lib/zabbix
    depends_on:
      - zabbix-db

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    environment:
      ZBX_SERVER_HOST: zabbix-server
      DB_SERVER_HOST: zabbix-db
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbixpass
      POSTGRES_DB: zabbix
    ports:
      - "8080:8080"
    volumes:
      - zabbix-web-data:/var/lib/zabbix
    depends_on:
      - zabbix-server

  zabbix-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbixpass
      POSTGRES_DB: zabbix
    volumes:
      - zabbix-db-data:/var/lib/postgresql/data

  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_HOSTNAME: zabbix-agent
    ports:
      - "10050:10050"
    depends_on:
      - zabbix-server

  zabbix-exporter:
    image: ghcr.io/shdubna/zabbix_exporter:latest
    command:
      - --zabbix_addr=zabbix-server
      - --zabbix_port=10051
    ports:
      - "9051:9051"
    depends_on:
      - zabbix-server

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  zabbix-server-data:
  zabbix-web-data:
  zabbix-db-data:
  prometheus-data:
  grafana-storage:
