name: Deploy Docker Compose

on:
  push:
    branches:
      - feature/workflow-local

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List files in repository
      run: dir

    - name: Criar diretório para os arquivos de deploy, se não existir
      run: |
        if not exist C:\projects\gerenciamento mkdir C:\projects\gerenciamento
      shell: cmd

    - name: Transferir docker-compose.yml e prometheus.yml para o diretório de deploy
      run: |
        copy docker-compose.yml C:\projects\gerenciamento\
        copy prometheus.yml C:\projects\gerenciamento\
      shell: cmd

    - name: Deploy Docker Compose
      run: |
        docker-compose down
        docker-compose build --no-cache
        docker-compose up -d
      shell: cmd
