name: Deploy Docker Compose

on:
  push:
    branches:
      - main  # Altere para a branch que deseja monitorar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List files in repository
      run: ls -la

    - name: Copy Docker Compose file to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: 'docker-compose.yml'
        target: '~/deploy/'

    - name: Deploy Docker Compose
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/deploy/
          docker-compose down
          docker-compose up -d
